version: 0.2

# Many BUILD ENVIRONMENT VARIABLES are specified in the template-pipeline.yml template.
# Search for 'EnvironmentVariables' under AWS::CodeBuild::Project in the template.
# 
# You can also run the command `printenv`

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:

      - ls -l -a

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

      - python --version

      # Set npm caching (This 'offline' cache is still tar zipped, but it helps.) - https://blog.mechanicalrock.io/2019/02/03/monorepos-aws-codebuild.html
      - npm config -g set prefer-offline true
      - npm config -g set cache /root/.npm
      - npm config get cache

  pre_build:
    commands:

      # Display the current value of NODE_ENV
      - echo "NODE_ENV is $NODE_ENV"
      
      # Install dependencies needed for application
      - ls -l -a
      - cd application-infrastructure/src
      - npm install

      # FAIL the build if npm audit has vulnerabilities it can't fix
      # Perform a fix to move us forward, then check to make sure there were no unresolved high fixes
      - npm audit fix --force
      - npm audit --audit-level=high
      
      # Go back to application-infrastructure directory
      - cd ..
      
  build:
    commands:

      # There is sometimes a bug that causes the alias to not be updated correctly (see comment in template.yml for AppFunction.Properties.AutoPublishCodeSha256)
      - python3 ./build-scripts/update_template_timestamp.py template.yml

      # Use CloudFormation to package the application infrastructure and code that was placed in the S3 Artifacts Bucket (usually something like `cf-artifacts-<region>-<account-id>` or `cf-templates-randomchars-<region>`).
      - aws cloudformation package --template template.yml --s3-bucket $S3_ARTIFACTS_BUCKET --output-template template-export.yml

      # Do a search/replace using the linux sed command in the template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's|\$AWS_PARTITION\$|'${AWS_PARTITION}'|g;s|\$AWS_REGION\$|'${AWS_REGION}'|g;s|\$AWS_ACCOUNT\$|'${AWS_ACCOUNT}'|g;s|\$PREFIX\$|'${PREFIX}'|g;s|\$PROJECT_ID\$|'${PROJECT_ID}'|g;s|\$STAGE_ID\$|'${STAGE_ID}'|g;s|\$REPOSITORY\$|'${REPOSITORY}'|g;s|\$REPOSITORY_BRANCH\$|'${REPOSITORY_BRANCH}'|g;s|\$DEPLOY_ENVIRONMENT\$|'${DEPLOY_ENVIRONMENT}'|g;s|\$ALARM_NOTIFICATION_EMAIL\$|'${ALARM_NOTIFICATION_EMAIL}'|g;s|\$PARAM_STORE_HIERARCHY\$|'${PARAM_STORE_HIERARCHY}'|g' template-configuration.json

      # list files in the artifacts
      - ls -l -a

artifacts:
  files:
    - 'application-infrastructure/**/*'

# add cache
cache:
  paths:
    - '/root/.npm/**/*'